/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wzq_pthreaddemo_PthreadUtil */

#ifndef _Included_com_wzq_posixthread_PthreadUtil
#define _Included_com_wzq_posixthread_PthreadUtil
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT void JNICALL Java_com_wzq_posixthread_PthreadUtil_nativeInit(JNIEnv *env, jobject obj);
void  Java_com_wzq_posixthread_PthreadUtil_nativeWorker(JNIEnv *env, jobject obj, jint threadIds, jint iteratations);

JNIEXPORT void JNICALL Java_com_wzq_posixthread_PthreadUtil_nativeFree(JNIEnv *env, jobject obj);

//JNIEXPORT void JNICALL Java_com_wzq_posixthread_PthreadUtil_nativeWorker(JNIEnv *env, jobject obj, jint threadIds, jint iteratations);
JNIEXPORT void JNICALL Java_com_wzq_posixthread_PthreadUtil_posixThreads(JNIEnv *env, jobject obj, jint threadIds, jint iteratations);
#ifdef __cplusplus
}
#endif
#endif
